import { motion } from "framer-motion";
import { FileText, Download, Printer, Share2, RefreshCw } from "lucide-react";
import Button from "../common/Button";

export function ReportViewer({ title = "Financial Report Preview" }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"
    >
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <p className="text-sm uppercase tracking-[0.2em] text-slate-500">
            Report Preview
          </p>
          <h3 className="text-xl font-semibold text-slate-900 dark:text-white">
            {title}
          </h3>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="secondary" size="sm" icon={Printer}>
            Print
          </Button>
          <Button variant="secondary" size="sm" icon={Download}>
            Export PDF
          </Button>
          <Button variant="secondary" size="sm" icon={Share2}>
            Share
          </Button>
          <Button variant="secondary" size="sm" icon={RefreshCw}>
            Refresh
          </Button>
        </div>
      </div>

      <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-800/60">
        <div className="flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-white">
          <FileText className="h-4 w-4" /> Summary
        </div>
        <div className="mt-3 grid gap-3 md:grid-cols-3">
          <div className="rounded-xl bg-white p-3 dark:bg-slate-900">
            <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
              Period
            </p>
            <p className="mt-1 font-semibold text-slate-900 dark:text-white">
              June 2026
            </p>
          </div>
          <div className="rounded-xl bg-white p-3 dark:bg-slate-900">
            <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
              Records
            </p>
            <p className="mt-1 font-semibold text-slate-900 dark:text-white">
              128 entries
            </p>
          </div>
          <div className="rounded-xl bg-white p-3 dark:bg-slate-900">
            <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
              Generated By
            </p>
            <p className="mt-1 font-semibold text-slate-900 dark:text-white">
              Finance Admin
            </p>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
